package ch.uzh.ifi.hase.soprafs21.entity;
import javax.persistence.*;
import java.io.Serial;
import java.io.Serializable;
import java.util.List;

// Basic implementation of Game entity. Has a unique, autogenerated ID, Takes a host, and a list of players.
// Its further logic is yet to be implemented

@Entity
@Table(name = "GAME")
public class Game implements Serializable {

    // the serialVersionUID makes sure that the sender and receiver of a serialized object have loaded the same object
    @Serial
    private static final long serialVersionUID = 3L;


    // id will be the same as the lobby ID where the game was iniialized
    @Id
    private Long id;

    // is given the same host from the lobby that started the game
    @Column(nullable = false)
    private String host;

    @Column
    private int currentPlayer = 0; //keeps track who is the current player

    @Column
    private boolean gameDirection = true; //true = clockwise

    @ElementCollection
    private List<Long> playerList;

    @Column
    private String currentColor;

    @Column
    private String currentValue;

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public void setPlayerList(List<Long> playerList) {
        this.playerList = playerList;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHost() {
        return host;
    }

    public void setHost(String host) {
        this.host = host;
    }

    public List<Long> getPlayerList() {
        return playerList;
    }

  /** public Hand getHandByPlayerId(int playerId){
        return userService.getUserById(playerID).getHand();
    }

    public Deck getCardStack() {
        return deck;
    }
   */



    public String getCurrentColor() {
        return currentColor;
    }

    public void setCurrentColor(String wishedColor) {
        this.currentColor = wishedColor;
    }


    public String getCurrentValue() {
        return currentValue;
    }

    public void setCurrentValue(String currentValue) {
        this.currentValue = currentValue;
    }

    public void setCurrentPlayer(int currentPlayer) {
        this.currentPlayer = currentPlayer;
    }

    public long getCurrentPlayerId() {
        return playerList.get(currentPlayer);
    }

    public void setCurrentPlayerPlusOne() {
        if (gameDirection) {
            this.currentPlayer = (this.currentPlayer + 1) % playerList.size();
        } else{
            this.currentPlayer = (this.currentPlayer - 1);
            if(currentPlayer == -1){
                this.currentPlayer = playerList.size()-1;
            }
            System.out.println(currentPlayer);
            System.out.println(gameDirection);
        }
    }


    public void reverseGameDirection(){
        this.gameDirection = !gameDirection;
        System.out.println(gameDirection);
    }

    public boolean getGameDirection(){
        return gameDirection;
    }


public int getCurrentPlayer() {
        return currentPlayer;
}



    /**
    @Column(nullable = false)
    private String gamemode; */

    /**
    public ArrayList<Hand> players = new ArrayList<Hand>();
    public ArrayList<Card> playedCards = new ArrayList<Card>();
    public boolean gameDirection = false; //true = clockwise

    //index of players ArrayList
    public int currentPlayer = 0;



    public void setPlayers(Hand hand){
        this.players.add(hand);
    }


    public void initializeHands() {
        for (Hand i : players) {
            i.initializeHand();
        }
    }



     */

}
