package ch.uzh.ifi.hase.soprafs21.entity;
import javax.persistence.*;
import java.io.Serial;
import java.io.Serializable;
import java.util.List;

/**
 * Internal Lobby Representation
 * This class composes the internal representation of the lobby and defines how the lobby is stored in the database.
 * Every variable will be mapped into a database field with the @Column annotation
 * - nullable = false -> this cannot be left empty
 * - unique = true -> this value must be unqiue across the database -> composes the primary key
 */


@Entity
@Table(name = "LOBBY")
public class Lobby implements Serializable {

    // the serialVersionUID makes sure that the sender and receiver of a serialized object have loaded the same object
    @Serial
    private static final long serialVersionUID = 2L;


    // id is a autogenerated primary key
    @Id
    @GeneratedValue
    private Long id;

    @Column(nullable = false)
    private String host;

    @Column(nullable = false)
    private boolean isInGame;

    @ElementCollection
    private List<String> PlayerList;

    @Column(nullable = false)
    private String gamemode;

    public void setId(Long id) {
        this.id = id;
    }

    public void setHost(String host) {
        this.host = host;
    }

    public void setPlayerList(List<String> PlayerList) {
        this.PlayerList = PlayerList;
    }

    public void setGamemode(String gamemode) {
        this.gamemode = gamemode;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public boolean isInGame() {
        return isInGame;
    }

    public void setInGame(boolean inGame) {
        isInGame = inGame;
    }

    public Long getId() {
        return id;
    }

    public String getHost(){ return host;
    }

    public List<String> getPlayerList() {
        return PlayerList;
    }

   public String getGamemode() {
        return gamemode;
    }
}






